participants=10;
%processedfolder={'variablesout\';};
%define array for all subjects
folder={'C:\Users\sonal\Documents\MATLAB\pd\sub1\';
             'C:\Users\sonal\Documents\MATLAB\pd\sub2\';
             'C:\Users\sonal\Documents\MATLAB\pd\sub3\';
             'C:\Users\sonal\Documents\MATLAB\pd\sub4\';
              'C:\Users\sonal\Documents\MATLAB\pd\sub5\';
              'C:\Users\sonal\Documents\MATLAB\pd\sub6\';
              'C:\Users\sonal\Documents\MATLAB\pd\sub7\';
              'C:\Users\sonal\Documents\MATLAB\pd\sub9\';
              'C:\Users\sonal\Documents\MATLAB\pd\sub10\';
              'C:\Users\sonal\Documents\MATLAB\pd\sub11\';
             % 'C:\Users\sonal\Documents\MATLAB\pd\vp\';
             };
sublist={'sub1';
              'sub2';
              'sub3';
              'sub4';
              'sub5';
              'sub6';
              'sub7';
              'sub9';
              'sub10';
              'sub11';
              %'vp';
             };
type=       {'_mvl';
             '_mvr';
             '_svl';
             '_svr';
             '_coml';
             '_comr';
             };